version: '3.8'
services:

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring-with-mysql
    networks:
      - rede-spring-with-mysql
    volumes:
      - volume-spring-with-mysql:/var/lib/mysql

  app:
    build:
      context: ./app
    networks:
      - rede-spring-with-mysql
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysqldb

networks:
  rede-spring-with-mysql:
volumes:
  volume-spring-with-mysql: